# Generated by Django 3.2 on 2021-06-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='', max_length=200)),
                ('c_email', models.EmailField(default='', max_length=200)),
                ('c_cno', models.CharField(default='', max_length=50)),
                ('c_add', models.TextField(default='')),
                ('join_date', models.DateField(auto_now=True, null=True)),
                ('profile', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='Com_Prof/')),
                ('c_pass', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
