# Generated by Django 3.2 on 2021-07-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_company_customers_cust_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nm', models.CharField(default='', max_length=200)),
                ('prod_price', models.PositiveIntegerField(default=0)),
                ('prod_qty', models.PositiveIntegerField(default=0)),
                ('prod_img', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='ProductPic/')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company_details')),
            ],
        ),
    ]
